### ISSUE TITLE
merge openmeteopy into python-requests

### ISSUE THREAD

**Issue by m0rp43us** [open-meteo/python-requests#34]
Hello,

I can add a third version based on the sdk schemas created & add more functionnalities.

**Comment by patrick-zippenfenig** [comment]
Dear @m0rp43us,

sorry for not proactively reaching out. This python client is only a very shim layer and does not offer much functionally except decoding the FlatBuffer binary format (barely 30 lines of [code](https://github.com/open-meteo/python-requests/blob/main/openmeteo_requests/Client.py)). I am still considering if this is the best way forward as this schema may complicate usage. 

Could you have a look if the SDK schema with FlatBuffers makes sense for `openmeteopy`? Depending on the design, it may not require a new major version bump

**Comment by m0rp43us** [comment]
Dear @patrick-zippenfenig ,
I took a look on the sdk and it seems to me that there is a way to integrate FlatBuffers.
I will release a first stable version of the Python library (with tests and a Pypi release) at the beginning of 2024.
I do like the FlatBuffers optimization choice and also the models,makes everything much more simple regarding sdks.
