### ISSUE TITLE
openmateo_requests import fails

### ISSUE THREAD

**Issue by pfriedland** [open-meteo/python-requests#39]
Python 3.9.18 (main, Aug 24 2023, 18:16:58)
[Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmeteo_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pfriedland/Documents/projects/self/weather/openmeteo_requests.py", line 10, in <module>
    openmeteo = openmeteo_requests.Client(session = retry_session)
AttributeError: partially initialized module 'openmeteo_requests' has no attribute 'Client' (most likely due to a circular import)
>>>

I've tried different python versions 3.9, 3.11 on macos

**Comment by patrick-zippenfenig** [comment]
What was the issue? Some kind of venv package install mixup?

**Comment by pfriedland** [comment]
lol, I named the file openmateo_requests.py.
